version: "3.5"

services:
  mysql-db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: definitions
      MYSQL_USER: greg
      MYSQL_PASSWORD: egu
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysql -ptest123 -e 'select 1'"]
      interval: 5s
      retries: 50

  api:
    image: node:12
    build: ./api
    depends_on:
      - mysql-db
    links:
      - "mysql-db:mysql"
    ports:
      - 8080:8080
      - 443:443
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: definitions
      PORT: 8080
